In [2]:
import numpy as np

In [43]:
## Now finding average and mean
randNumbers = np.random.random((5,6))
a = randNumbers.mean()
b = np.average(randNumbers) # Taking average of matrix (without specifying any axis)
print(randNumbers)
print(a)
print(b)
print(a == b)

[[0.32474545 0.12623163 0.15423802 0.52386927 0.53907221 0.74243466]
 [0.7095291  0.76054194 0.19737168 0.41174468 0.3770703  0.23545505]
 [0.49383477 0.89600139 0.36543599 0.67710661 0.48342752 0.30180185]
 [0.44478269 0.13713363 0.69722223 0.17302111 0.2018117  0.21713712]
 [0.67518815 0.32075697 0.31332391 0.31406396 0.08203681 0.79621335]]
0.4230867918618661
0.4230867918618661
True


In [51]:
## Now finding average according to axis
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
#wt = np.array([1,2,3])
avg = np.average(matrix, axis = 0)
avg

array([4., 5., 6.])

In [55]:
## Now using numpy.bincount
#In an array of +ve integers, the numpy.bincount() method counts the occurrence of each element. 
# Each bin value is the occurrence of its index
number = [1,2,2,5,5,6,3,4,0,8]
bin = np.bincount(number)
print("Bincount Output \n", bin)
print("Bincount tells us the number of occurences of the index in the array")

Bincount Output 
 [1 1 2 1 1 2 1 0 1]
Bincount tells us the number of occurences of the index in the array


In [3]:
# linspace used to create elements within a certain range and a number of them
# It takes 3 arguements with range and make 10 elements in numpy array, equally spaced from each other
someNum = np.linspace(1,50,10)
print(someNum)

[ 1.          6.44444444 11.88888889 17.33333333 22.77777778 28.22222222
 33.66666667 39.11111111 44.55555556 50.        ]


In [4]:
# np.arange create array with incrementing values
arangingArray = np.arange(1,10,2)
arangingArray

array([1, 3, 5, 7, 9])

In [5]:
# Creating eye matrix
eyeMatrix = np.eye(4) 
eyeMatrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
np.zeros((2, 3)) # For creation of 2d matrix with 2 rows and 3 columns of zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# Generate a random matrix with shape (rows, cols)
random_matrix = np.random.random((3,4))
print(random_matrix)
print('\n')
np.empty(3)

[[0.07349092 0.75966963 0.85188128 0.15981484]
 [0.12307573 0.85577599 0.8755997  0.68071739]
 [0.21098853 0.3935349  0.94671295 0.59870559]]




array([1.07777291e-311, 0.00000000e+000, 4.94065646e-324])

In [9]:
# Making copy of numpy array
arr = np.array([1,2,3,4])
copyArr = arr.copy() # This is deep copy
viewArr = arr.view() # This is shallow copy
arr[2] = 15
print(arr)
print(copyArr)
print(viewArr)

[ 1  2 15  4]
[1 2 3 4]
[ 1  2 15  4]


In [15]:
# Concatenating numpy of different types
arr = np.array([[1, 8, 3], [3,5,7]])
arr2 = np.array([['g','g','g'], ['g','g','g'] ]) 
combinedArr = np.concatenate((arr, arr2), axis = 0)
combinedArr

array([['1', '8', '3'],
       ['3', '5', '7'],
       ['g', 'g', 'g'],
       ['g', 'g', 'g']], dtype='<U11')

In [18]:
## Making stack in array
arr1 = np.array([1, 8, 3, 3, 5])
arr2 = np.array([5,4,85,1,45])
newArr = np.vstack((arr1, arr2))
newArr2 = np.hstack((arr1, arr2))
print(newArr,"\n the dimension of array is {}".format(newArr.ndim), '\n')
print(newArr2)

[[ 1  8  3  3  5]
 [ 5  4 85  1 45]] 
 the dimension of array is 2 

[ 1  8  3  3  5  5  4 85  1 45]


In [19]:
# Splitting the array into 4 uNequal parts along the first axis (axis=0)
array = np.arange(6)
result = np.array_split(array, 4)
result

[array([0, 1]), array([2, 3]), array([4]), array([5])]

In [20]:
## Comparison of 2 arrays
an_array = np.array([[1, 2], [3, 4]])
another_array = np.array([[1, 2], [4, 3]])

print(another_array == an_array)
# This tells us about the relation with list items individually in the given manner
# To make net decision use:
compar = another_array == an_array
print("Result conclusion is: ",compar.all())

[[ True  True]
 [False False]]
Result conclusion is:  False


In [39]:
## Doing bitwise binary operations 
# Doing binary operations
arr1 = np.array([5,8,10])
arr2 = np.array([10,12,9])
ansOr = np.bitwise_or(arr1, arr2)
ansAnd = np.bitwise_and(arr1, arr2)
ansXor = np.bitwise_xor(arr1, arr2)
print(ansOr)
print(ansAnd)
print(ansXor)

[15 12 11]
[0 8 8]
[15  4  3]


In [56]:
## Using split operations in string
print(np.char.split('Hi how are you'))

['Hi', 'how', 'are', 'you']


In [64]:
## Reshaping of NumPy Array
arr = np.arange(1, 13.0) # In this as we have mentioned .0 so all the elements will be of type float
reshArr = np.reshape(arr, (3,4), order='F')
# In this way reshape is done such a way that columns are filled first
reshArr2 = np.reshape(arr, (3,4) , order='A')
# In this way reshape is done such a way that rows are filled first
print(reshArr)
print(reshArr2)

# By default order is 'C' which means the method which is faster and it is always 'A'
reshArr3 = np.reshape(arr, (3,4) , order='C')
print("Are both arrays after reshaping in order C and A are same: ", (reshArr2 == reshArr3).all() )

[[ 1.  4.  7. 10.]
 [ 2.  5.  8. 11.]
 [ 3.  6.  9. 12.]]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
Are both arrays after reshaping in order C and A are same:  True


In [66]:
## Now flattening a 2d array
mat = np.array([[1,2], [3,4],[5,6]])
print("The matrice shape is: ", mat.shape)
print(mat)
print("After flattening the matrice is: \n",mat.flatten(order = 'a'))

The matrice shape is:  (3, 2)
[[1 2]
 [3 4]
 [5 6]]
After flattening the matrice is: 
 [1 2 3 4 5 6]


In [76]:
## Using of split functions
# Use of vsplit function
arr = np.arange(9).reshape(3,3)
print(arr)
ex = np.vsplit(arr, 3)
print("\n", ex)
# This functions makes equal subarrays from original matrix 
hSpl = np.hsplit(arr, 3)
print(hSpl)
print("The type after reshaping is {} and inside it is {}".format(type(hSpl), type(hSpl[0])),)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

 [array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]
[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]
The type after reshaping is <class 'list'> and inside it is <class 'numpy.ndarray'>
