In [1]:
import numpy as np

In [5]:
# Doing binary operations
arr1 = np.array([5,8,10])
arr2 = np.array([10,12,9])
ans1 = np.bitwise_or(arr1, arr2)
ans2 = np.bitwise_and(arr1, arr2)
print(ans1)
print(ans2)

[15 12 11]
[0 8 8]


In [6]:
# Note for using np.right_shift() or np.left_shift() it done on numbers and not on np

In [8]:
# doing math operations
import math
sinValue = np.sin(arr1)
print("Cos value ", np.cos(arr1) )
print(sinValue)

Cos value  [ 0.28366219 -0.14550003 -0.83907153]
[-0.95892427  0.98935825 -0.54402111]


In [10]:
# Rounding of decimal
num = np.array([1.66588, 85.5845825, 45.5855145])
roundedVal = np.round_(num, decimals = 4)
print(roundedVal)

[ 1.6659 85.5846 45.5855]


In [16]:
## Using string operations
# Using split function
print(np.char.split('Hi how are you'))
print(np.char.split('Hihowareyo,u'), sep=',' )

['Hi', 'how', 'are', 'you']
['Hihowareyo,u']


In [17]:
print(np.char.join('-','Hi how are you'))

H-i- -h-o-w- -a-r-e- -y-o-u


In [23]:
# Counting the number of occurences of a string in a np string array
stri = np.array(['hi', 'hello', 'he', 'hi', 'hi'])
count = np.char.count(stri, 'hi')
print(count)
print(np.char.upper(stri))

[1 0 0 1 1]
['HI' 'HELLO' 'HE' 'HI' 'HI']


In [33]:
# Now can also check comparison of 2 string
# For checking of equal strings it check only for exactly same
print(np.char.equal('for', 'rof'))
# For comparison it check by alphabetic wise
print(np.char.less('rof', 'for')) # Here xy is greater than abbb as it checks the sum of values

False
False


### Reshaping NumPy array

In [59]:
# For reshaping the product of rows and columns must be equal to the number of original elements

In [98]:
arr = np.arange(1, 13.0)
print(arr.dtype)
print(arr)
reshArr = np.reshape(arr, (3,4))
reshArr2 = np.reshape(arr, (3,4) , order='a')
print(reshArr)
print(reshArr2)
orgArr = np.reshape(reshArr, (12))
print(orgArr)

float64
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [99]:
# While using resize() function it changes the shape of original array
# resize() works even if the number of element doesn't match the dimension --- It can truncate or replicate 

In [100]:
arr = np.arange(1,7)
print(arr)
print("The shape of array is: ", arr.shape)
abc = arr.resize(2,5)
print("The shape of new array is: ", arr.shape)
print(abc)
print(arr)
# arr.resize() returns NONE. It changes the original array and doesn't store the result anywhere
arr.resize(10)
print(arr)

[1 2 3 4 5 6]
The shape of array is:  (6,)
The shape of new array is:  (2, 5)
None
[[1 2 3 4 5]
 [6 0 0 0 0]]
[1 2 3 4 5 6 0 0 0 0]


In [101]:
# We can also explicitly change the shape of array by using arr.shape = (x,y)

In [103]:
arr1 = np.arange(1.,13.)
newArr1 = np.reshape(arr1, (4,3), order= 'c')
print(newArr1)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [104]:
# We can also change the order of reshape that whether reshaping using row or by column
# by using order = 'c' or by order = 'f' or by order = 'a'{automatic} 

In [132]:
mat = np.array([[1,2], [3,4],[5,6]])
print(mat.shape)
print(mat)
print(mat.flatten(order = 'a'))

(3, 2)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [141]:
## Using of split functions
# Use of vsplit function
arr = np.arange(9).reshape(3,3)
print(arr)
ex = np.vsplit(arr, 3)
print("\n", ex)
# This functions makes equal subarrays from original matrix 
hSpl = np.hsplit(arr, 3)
print(hSpl)
print("Other one is: \n", np.hsplit(arr,1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]

 [array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]
[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]
Other one is: 
 [array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])]
