# Learning Numpy Creation

In [22]:
# NumPy is homogenous multidimensional array
# Note -> 
# Techniques for making Numpy
"""
Conversion from other Python structures (i.e. lists and tuples)

Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

Replicating, joining, or mutating existing arrays

Reading arrays from disk, either from standard or custom formats

Creating arrays from raw bytes through the use of strings or buffers

Use of special library functions e.g., random
"""

'\nConversion from other Python structures (i.e. lists and tuples)\n\nIntrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)\n\nReplicating, joining, or mutating existing arrays\n\nReading arrays from disk, either from standard or custom formats\n\nCreating arrays from raw bytes through the use of strings or buffers\n\nUse of special library functions e.g., random\n'

In [23]:
import numpy as np

In [24]:
# Creation of numpy array from list

In [25]:
npList = np.array([1,2,3,4])
print(type(npList))
print(npList.ndim)
for i in npList:
    print(i, end = " ")

<class 'numpy.ndarray'>
1
1 2 3 4 

In [26]:
a2d = np.array([[1,2], [3,4], [5,6]])
# Here list of list will give 2d numpy array
# np.array takes input as a list then in that list we are giving multiple lists
print(type(a2d))
print(a2d.ndim)
a2d

<class 'numpy.ndarray'>
2


array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
# Usage of dtype in numpy --> It tells about the datatype object

In [31]:
# Indexing of elements in numpy arrays
elem1 = npList[2]
elem2 = a2d[2,1] # This is a 2d array so this is the way for accessing 2d arrays
print(elem1, elem2)

3 6


In [39]:
ab = np.array([12,15,17], dtype = np.int8)
# Here dtype tells about the data type
# Here we have assigned the data type on our own
# Here it means that it of type int and represented by 8 bit signed integer
ab

array([12, 15, 17], dtype=int8)

In [53]:
numb1 = np.array([145,758,477], dtype = np.uint32) # this is unsigned int which has double the range but only in positive
numb2= np.array([14,78,477], dtype = np.uint32)
dif = numb1 - numb2
add = numb1 + numb2
mul = numb1 * numb2
print(dif)
print(add)
print(type(add), add.dtype)
print(mul)

[131 680   0]
[159 836 954]
<class 'numpy.ndarray'> uint32
[  2030  59124 227529]


In [50]:
print(numb1 == numb2)
# In this way we can directly compare also about the contents of 

[False False  True]


# Intrinsic NumPy array creation

In [58]:
number = np.arange(10)
number2 = np.arange(5,15)
# Takes 2 input start and stop
# Last number not considered
print(number)
print(number2)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]


In [62]:
# linspace used to create elements within a certain range and a number of them
# It takes 3 arguements with range and make 10 elements in numpy array, equally spaced from each other
someNum = np.linspace(1,50,10)
print(someNum)

[ 1.          6.44444444 11.88888889 17.33333333 22.77777778 28.22222222
 33.66666667 39.11111111 44.55555556 50.        ]


In [64]:
# np.arange create array with incrementing values
arangingArray = np.arange(1,10,2)
arangingArray

array([1, 3, 5, 7, 9])

In [66]:
# np.eye defines 2d matrix with i = j as 1 else 0

In [68]:
eyeMatrix = np.eye(4) 
eyeMatrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [82]:
mat1 = np.diag([1,2,3])
mat2 = np.diag([[1,2], [3,4]])
print(mat1)
print("Space Here")
print(mat2)
print(f'The dimension of mat1 is {np.ndim(mat1)}')
print(f'The dimension of mat2 is {np.ndim(mat2)}')
mat3 = np.diag([1,2,3,4],2) # This code adds n number of rows in left of the matrix and n number of rows at the bottom
print(mat3)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
Space Here
[1 4]
The dimension of mat1 is 2
The dimension of mat2 is 1
[[0 0 1 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 3 0]
 [0 0 0 0 0 4]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [83]:
# In np.diag if given only 1d array then it creates a 2d matrix with diagonal elements as the list elements
# If given a 2d array then gives 

In [85]:
np.zeros((2, 3)) # For creation of 2d matrix with 2 rows and 3 columns of zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [87]:
np.empty(3) # Random matrix 

array([1.11941284e-311, 0.00000000e+000, 6.95271922e-310])

In [88]:
# Using of reshape is to change the dimensions of it
reshapeArr = np.arange(10)
print(reshapeArr)


[0 1 2 3 4 5 6 7 8 9]
