# Array Manipulation

### Copy and View

In [1]:
# Concept of view and copy
#. No copy by assigning
import numpy as np
arr = np.array([1,2,3,4])
arrC = arr
print("The id of arr1 is ",id(arr))
print("The id of shallow copy of ar1 is ",id(arrC))
print(arr)
print(arrC)


The id of arr1 is  1845284227280
The id of shallow copy of ar1 is  1845284227280
[1 2 3 4]
[1 2 3 4]


In [2]:
arr[2] = 5
print(arr)
print(arrC) # Both are changed

[1 2 5 4]
[1 2 5 4]


In [3]:
# Now making view 
# This is the view of the original array and does not have its own data
# This is the shallow copy
viewArr = arr.view()
print("The id of view is",id(viewArr))
print("The id of original is",id(arr))
print(viewArr)
viewArr[2] = 8
print(viewArr)
print(arr)
# In this they have different address but changing one thing will also change the other

The id of view is 1845289070160
The id of original is 1845284227280
[1 2 5 4]
[1 2 8 4]
[1 2 8 4]


In [4]:
copyArr = arr.copy() # This is the command for making another copy of array
arr[3] = 10
print(arr)
print(copyArr)
print(copyArr.base)

[ 1  2  8 10]
[1 2 8 4]
None


### Appending values in numpy array

In [14]:
arr = np.array([1, 8, 3, 3, 5])
print('Original Array : ', arr)
 
# appending to the array
arr = np.append(arr, [7,5])  # In the arguement give the name of original array anf list of items to be added
print('Array after appending : ', arr)

Original Array :  [1 8 3 3 5]
Array after appending :  [1 8 3 3 5 7 5]


In [37]:
arr2D = np.array([[1,5,7], [4,8,10]])
print(arr2D)
arrEx = np.array([[5,7,10], [4,5,6]])
newArr2d = np.append(arr2D, arrEx, axis = 1) # By using append it will always give a 1d array
print(newArr2d)

[[ 1  5  7]
 [ 4  8 10]]
[[ 1  5  7  5  7 10]
 [ 4  8 10  4  5  6]]


In [36]:
arr = np.array([[1, 8, 3], [3,5,7]])
print(arr)
arr2 = np.array([['g','g','g'], ['g','g','g'] ]) 
combinedArr = np.concatenate((arr, arr2), axis = 0)
print(combinedArr)
# When joining it converts the previous array also into the same type as of this

[[1 8 3]
 [3 5 7]]
[['1' '8' '3']
 ['3' '5' '7']
 ['g' 'g' 'g']
 ['g' 'g' 'g']]


In [43]:
# Concatenate is one of the method for joining of arrays
# For arguement it takes a tuple of arrays and the axis

In [45]:
arr1 = np.array([1, 8, 3, 3, 5])
arr2 = np.array([5,4,85,1,45])
newArr = np.vstack((arr1, arr2))
newArr2 = np.hstack((arr1, arr2))
newarr3 = np.stack((arr1, arr2), axis = 0)
# Takes input as a tuple of arrays
print("Vertical stack: ", newArr)
print("Horizontal Stack", newArr2)
print(newarr3)

Vertical stack:  [[ 1  8  3  3  5]
 [ 5  4 85  1 45]]
Horizontal Stack [ 1  8  3  3  5  5  4 85  1 45]
[[ 1  8  3  3  5]
 [ 5  4 85  1 45]]


In [46]:
# Third method is by numpy.block

#### Splitting of NumPy arrays

In [47]:
"""
Split numpy array using numpy.split()
Split numpy array using numpy.array_split()
Splitting NumPy 2D Arrays
Split numpy array using numpy.vsplit()
Split numpy array using numpyhsplit()
Split numpy arrayusing numpy.dsplit()
"""

'\nSplit numpy array using numpy.split()\nSplit numpy array using numpy.array_split()\nSplitting NumPy 2D Arrays\nSplit numpy array using numpy.vsplit()\nSplit numpy array using numpyhsplit()\nSplit numpy arrayusing numpy.dsplit()\n'

In [52]:
array = np.arange(6)
# Splitting the array into 2 equal parts along the first axis (axis=0)
result = np.split(array, 3)

print("Array:")
print(array)
print("Result after numpy.split():")
print(result)


Array:
[0 1 2 3 4 5]
Result after numpy.split():
[array([0, 1]), array([2, 3]), array([4, 5])]


In [53]:
array = np.arange(6)
# Splitting the array into 4 uNequal parts along the first axis (axis=0)
result = np.array_split(array, 4)

print("Array:")
print(array)
print("Result after numpy.split():")
print(result)


Array:
[0 1 2 3 4 5]
Result after numpy.split():
[array([0, 1]), array([2, 3]), array([4]), array([5])]


In [61]:
# Creating a 2D array
array = np.array([[3, 2, 1], [8, 9, 7], [4, 6, 5]])

# Splitting the array into 3 equal parts along the second axis (axis=1)
result = np.split(array, 3, axis = 1)

print("2D Array:")
print(array)
print("\nResult after numpy.split() along axis=1:")
print(result)
# 3,8,4 are one array and similarly others

2D Array:
[[3 2 1]
 [8 9 7]
 [4 6 5]]

Result after numpy.split() along axis=1:
[array([[3],
       [8],
       [4]]), array([[2],
       [9],
       [6]]), array([[1],
       [7],
       [5]])]


### Comparison of values in NumPy

In [80]:
an_array = np.array([[1, 2], [3, 4]])
another_array = np.array([[1, 2], [4, 3]])

print(another_array == an_array)
# This tells us about the relation with list items individually in the given manner
# To make net decision use:
compar = another_array == an_array
print("Result conclusion is: ",compar.all())
# Another way is using 
print(np.array_equal(an_array, another_array))

[[ True  True]
 [False False]]
Result conclusion is:  False
False


In [83]:
arr1 = np.array([[1,2,3],[4,5,6]])
arrX = np.array([[5,2,3],[4,8,6]])
compari = arr1 < arrX
print(compari)
print("Hello")
print(np.greater_equal(arr1, arrX))

[[ True False False]
 [False  True False]]
Hello
[[False  True  True]
 [ True False  True]]


### Union of Arrays

In [88]:
# Union of 1d array and also convert into 1d
arr1 = np.array([[1,2], [89,5]])
arr2 = np.array([[5,7],[90,1]])
print(np.union1d(arr1,arr2))

[ 1  2  5  7 89 90]


In [90]:
arrT = np.array(([5,7],[90,1])) # We can also input list of lists or tuple of lists
print(arrT)

[[ 5  7]
 [90  1]]


In [94]:
## Finding unique rows from a 2d matrix
## Similarly it is for 1d array
array2D = np.array([[1,2,3,4], [5,6,7,4], [5,8,1,18]])
print(np.unique(array2D, return_counts= True, return_inverse= True))

(array([ 1,  2,  3,  4,  5,  6,  7,  8, 18]), array([0, 1, 2, 3, 4, 5, 6, 3, 4, 7, 0, 8], dtype=int64), array([2, 1, 1, 2, 2, 1, 1, 1, 1], dtype=int64))


In [104]:
# Trimming of zeros
# It means removing 0 from front or from end
zeroArray = np.array([0,0,0,0,1,2,3,4,5,0,0,0,])
print(np.trim_zeros(zeroArray,"bf"))
print(np.trim_zeros(zeroArray,"f"))

[1 2 3 4 5]
[1 2 3 4 5 0 0 0]
