In [1]:
## Indexing and slicing in numpy arrays

In [2]:
import numpy as np

In [8]:
arr = np.arange(10)
newArr = arr[np.array([3,4,-1])]
print(newArr) # This is indexing
print(type(newArr)) # -ve index start from end

[3 4 9]
<class 'numpy.ndarray'>


In [10]:
newArr1 = arr[:5] # Slicing
print(newArr1)

[0 1 2 3 4]


In [17]:
mat = np.arange(9).reshape(3,3)
print(mat)
mat2 = mat[0:2,0:2] # First one is for along the row (horizontal) and second is for along the column (vertical) 
print (mat2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1]
 [3 4]]


In [20]:
## Calculating std dev
stDev = np.std(mat)
print("The standard deviation of matrix is: {}".format(stDev))

The standard deviation of matrix is: 2.581988897471611


In [21]:
## Usage of Linear Algebra 
from numpy import linalg as LA

In [33]:
array = np.arange(6,15).reshape(3,3)
print(array)
print("Rank: ", LA.matrix_rank(array))
print("\nTrace of A:", np.trace(array))
 
# Determinant of a matrix
print("\nDeterminant of A:", np.linalg.det(array))

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
Rank:  2

Trace of A: 30

Determinant of A: 0.0
